name: C++ CI with GoogleTest

on:
  push:
    branches:
      - jmoreira00
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up C++ and install dependencies
        uses: actions/setup-cpp@v1
        with:
          gcc: '11'
          g++: '11'

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ make

      - name: Build and run tests
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ctest --output-on-failure

