name: C++ CI with GoogleTest

on:
  push:
    branches:
      - jmoreira00
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: actions/setup-cmake@v3 # This sets up CMake (which is needed for building)

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ make

      - name: Build and run tests
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ctest --output-on-failure

