name: C++ CI with GoogleTest

on:
  push:
    branches:
      - bmonteir
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ make

      - name: Build and run tests
        run: |
          cd Modules/Module02/Exercise_01
          rm -rf build
          mkdir build
          cd build
          cmake ..
          make
          ctest --output-on-failure